name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone rep
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: node -v
      - uses: actions/hello-world-javascript-action@main
